
const years= ['y2024','y2025','y2026','y2027','y2028','y2029','y2030'];

const areaCodes =[["uc","UnitedChina"],
    ["in","India"],
    ["us","United States"],
    ["id","Indonesia"],
    ["pk","Pakistan"],
    ["br","Brazil"],
    ["ng","Nigeria"],
    ["uu","UnitedUkraine"],
    ["bd","Bangladesh"],
    ["mx","Mexico"],
    ["jp","Japan"],
    ["et","Ethiopia"],
    ["ph","Philippines"],
    ["eg","Egypt"],
    ["vn","Vietnam"],
    ["cd","DR Congo"],
    ["ir","Iran"],
    ["tr","Turkey"],
    ["de","Germany"],
    ["ka","United Korea"],
    ["fr","France"],
    ["uk","United Kingdom"],
    ["th","Thailand"],
    ["za","South Africa"],
    ["tz","Tanzania"],
    ["it","Italy"],
    ["mm","Myanmar"],
    ["co","Colombia"],
    ["ke","Kenya"],
    ["ar","Argentina"],
    ["es","Spain"],
    ["dz","Algeria"],
    ["sd","Sudan"],
    ["ug","Uganda"],
    ["iq","Iraq"],
    ["ca","Canada"],
    ["pl","Poland"],
    ["ma","Morocco"],
    ["uz","Uzbekistan"],
    ["sa","Saudi Arabia"],
    ["pe","Peru"],
    ["af","Afghanistan"],
    ["my","Malaysia"],
    ["ao","Angola"],
    ["mz","Mozambique"],
    ["gh","Ghana"],
    ["ye","Yemen"],
    ["np","Nepal"],
    ["ve","Venezuela"],
    ["ci","Ivory Coast"],
    ["mg","Madagascar"],
    ["au","Australia"],
    ["cm","Cameroon"],
    ["ne","Niger"],
    ["lk","Sri Lanka"],
    ["bf","Burkina Faso"],
    ["ml","Mali"],
    ["cl","Chile"],
    ["kz","Kazakhstan"],
    ["ro","Romania"],
    ["mw","Malawi"],
    ["zm","Zambia"],
    ["sy","Syria"],
    ["ec","Ecuador"],
    ["nl","Netherlands"],
    ["sn","Senegal"],
    ["gt","Guatemala"],
    ["td","Chad"],
    ["so","Somalia"],
    ["zw","Zimbabwe"],
    ["kh","Cambodia"],
    ["up","UnitedPalestine"],
    ["ss","South Sudan"],
    ["rw","Rwanda"],
    ["gn","Guinea"],
    ["bi","Burundi"],
    ["bj","Benin"],
    ["bo","Bolivia"],
    ["tn","Tunisia"],
    ["ht","Haiti"],
    ["be","Belgium"],
    ["jo","Jordan"],
    ["cu","Cuba"],
    ["gr","Greece"],
    ["do","Dominican Republic"],
    ["cz","Czech Republic"],
    ["se","Sweden"],
    ["pt","Portugal"],
    ["az","Azerbaijan"],
    ["hu","Hungary"],
    ["hn","Honduras"],
    ["tj","Tajikistan"],
    ["by","Belarus"],
    ["ae","United Arab Emirates"],
    ["pg","Papua New Guinea"],
    ["at","Austria"],
    ["ch","Switzerland"],
    ["sl","Sierra Leone"],
    ["tg","Togo"],
    ["py","Paraguay"],
    ["la","Laos"],
    ["ly","Libya"],
    ["rs","Serbia"],
    ["sv","El Salvador"],
    ["lb","Lebanon"],
    ["kg","Kyrgyzstan"],
    ["ni","Nicaragua"],
    ["bg","Bulgaria"],
    ["tm","Turkmenistan"],
    ["dk","Denmark"],
    ["cg","Congo"],
    ["cf","Central African Republic"],
    ["fi","Finland"],
    ["sg","Singapore"],
    ["no","Norway"],
    ["sk","Slovakia"],
    ["cr","Costa Rica"],
    ["nz","New Zealand"],
    ["ie","Ireland"],
    ["kw","Kuwait"],
    ["lr","Liberia"],
    ["om","Oman"],
    ["pa","Panama"],
    ["mr","Mauritania"],
    ["hr","Croatia"],
    ["ge","Georgia"],
    ["er","Eritrea"],
    ["uy","Uruguay"],
    ["mn","Mongolia"],
    ["ba","Bosnia and Herzegovina"],
    ["pr","Puerto Rico (United States)"],
    ["am","Armenia"],
    ["al","Albania"],
    ["qa","Qatar"],
    ["lt","Lithuania"],
    ["jm","Jamaica"],
    ["md","Moldova"],
    ["na","Namibia"],
    ["gm","Gambia"],
    ["bw","Botswana"],
    ["ga","Gabon"],
    ["ls","Lesotho"],
    ["si","Slovenia"],
    ["lv","Latvia"],
    ["mk","North Macedonia"],
    ["x1","Kosovo"],
    ["gw","Guinea-Bissau"],
    ["gq","Equatorial Guinea"],
    ["bh","Bahrain"],
    ["tt","Trinidad and Tobago"],
    ["ee","Estonia"],
    ["tl","East Timor"],
    ["mu","Mauritius"],
    ["sz","Eswatini"],
    ["dj","Djibouti"],
    ["fj","Fiji"],
    ["cy","Cyprus"],
    ["km","Comoros"],
    ["bt","Bhutan"],
    ["gy","Guyana"],
    ["sb","Solomon Islands"],
    ["mo","Macau (China)"],
    ["lu","Luxembourg"],
    ["me","Montenegro"],
    ["eh","Western Sahara"],
    ["sr","Suriname"],
    ["cv","Cape Verde"],
    ["mt","Malta"],
    ["bz","Belize"],
    ["bn","Brunei"],
    ["bs","Bahamas"],
    ["mv","Maldives"],
    ["x2","Northern Cyprus"],
    ["is","Iceland"],
    ["x3","Transnistria"],
    ["vu","Vanuatu"],
    ["bb","Barbados"],
    ["pf","French Polynesia (France)"],
    ["nc","New Caledonia (France)"],
    ["x4","Abkhazia"],
    ["st","São Tomé and Príncipe"],
    ["ws","Samoa"],
    ["lc","Saint Lucia"],
    ["gu","Guam (United States)"],
    ["cw","Curaçao (Netherlands)"],
    ["x5","Artsakh"],
    ["ki","Kiribati"],
    ["gd","Grenada"],
    ["aw","Aruba (Netherlands)"],
    ["vc","Saint Vincent and the Grenadines"],
    ["je","Jersey (British Crown Dependency)"],
    ["fm","Micronesia"],
    ["to","Tonga"],
    ["ag","Antigua and Barbuda"],
    ["sc","Seychelles"],
    ["vi","U.S. Virgin Islands (United States)"],
    ["im","Isle of Man (British Crown Dependency)"],
    ["ad","Andorra"],
    ["dm","Dominica"],
    ["ky","Cayman Islands (United Kingdom)"],
    ["bm","Bermuda (United Kingdom)"],
    ["gg","Guernsey (British Crown Dependency)"],
    ["gl","Greenland (Denmark)"],
    ["mh","Marshall Islands"],
    ["kn","Saint Kitts and Nevis"],
    ["fo","Faroe Islands (Denmark)"],
    ["x6","South Ossetia"],
    ["as","American Samoa (United States)"],
    ["mp","Northern Mariana Islands (United States)"],
    ["tc","Turks and Caicos Islands (United Kingdom)"],
    ["sx","Sint Maarten (Netherlands)"],
    ["li","Liechtenstein"],
    ["mc","Monaco"],
    ["gi","Gibraltar (United Kingdom)"],
    ["sm","San Marino"],
    ["mq","Saint Martin (France)"],
    ["ax","Åland (Finland)"],
    ["vg","British Virgin Islands (United Kingdom)"],
    ["pw","Palau"],
    ["ck","Cook Islands"],
    ["ai","Anguilla (United Kingdom)"],
    ["nr","Nauru"],
    ["wf","Wallis and Futuna (France)"],
    ["tv","Tuvalu"],
    ["x7","Saint Barthélemy (France)"],
    ["sh","Saint Helena"," Ascension and Tristan da Cunha (United Kingdom)"],
    ["pm","Saint Pierre and Miquelon (France)"],
    ["ms","Montserrat (United Kingdom)"],
    ["fk","Falkland Islands (United Kingdom)"],
    ["cx","Christmas Island (Australia)"],
    ["nf","Norfolk Island (Australia)"],
    ["nu","Niue"],
    ["tk","Tokelau (New Zealand)"],
    ["va","Vatican City"],
    ["cc","Cocos (Keeling) Islands (Australia)"],
    ["pn","Pitcairn Islands (United Kingdom)"],
    ["zz","global"]
];


//* Classification by law 
//* Classification other than by law
//* School-related classification

const divisions = [['a01','Constitution'],
    ['a02','Human rights'],
    ['a03','Economy'],
    ['a04','Environment'],
    ['a05','Education'],
    ['a06','Medical care'],
    ['a07','Welfare'],
    ['a08','Labor'],
    ['a09','Transportation'],
    ['a10','Housing'],
    ['a11','Disaster'],
    ['a12','Crime'],
    ['a13','National defense'],
    ['a14','Diplomacy'],
    ['a15','Others'],
    ['b01','Environment'],
    ['b02','Local community'],
    ['b03','Education, health and welfare'],
    ['b04','Work style'],
    ['b05','Impact of technology'],
    ['b06','Others'],
    ['c01','School building'],
    ['c02','Electronic devices'],
    ['c03','Bullying prevention measures'],
    ['c04','Internet'],
    ['c05','Connection with society'],
    ['c06','School rules'],
    ['c07','Educational content'],
    ['c08','Entrance examination system'],
    ['c09','Others']
];
